version: '2'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  cloudwatchexporter:
    image: quay.io/prometheus/cloudwatch-exporter
    container_name: cloudwatchexporter
    volumes:
      - ./config/prometheus/cloudwatch_config.yml:/config/cloudwatch_config.yml
    command:
      - '/config/cloudwatch_config.yml'
    expose:
      - 9106
    ports:
      - 9106:9106
  cloudwatchglobalexporter:
    image: quay.io/prometheus/cloudwatch-exporter
    container_name: cloudwatchglobalexporter
    volumes:
      - ./config/prometheus/us-east-1.yml:/config/us-east-1.yml
    command:
      - '/config/us-east-1.yml'
    expose:
      - 9106
    ports:
      - 9107:9106
  statsd:
    image: prom/statsd-exporter
    container_name: statsd
    volumes:
      - ./config/prometheus/statsd_mapping.yml:/tmp/statsd_mapping.yml
    command:
      - '--statsd.mapping-config=/tmp/statsd_mapping.yml'
    expose:
      - 9125
      - 9102
    ports:
      - 9125:9125/tcp
      - 9102:9102
      - 9125:9125/udp
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - statsd
      - cloudwatchexporter    
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=sigma
      - GF_USERS_ALLOW_SIGN_UP=false